openapi: 3.0.2
info:
  title: Bangumi Private API
  version: ''
  description: '`next.bgm.tv` 域名不支持跨域，'
servers:
  - url: https://next.bgm.tv
    description: Production server
paths:
  /p/login:
    post:
      tags:
        - Auth
      summary: 登录
      operationId: login
      description: >
        `h-captcha-response` 是 [hCaptcha
        的验证码](https://docs.hcaptcha.com/#add-the-hcaptcha-widget-to-your-webpage)


        site key 是 `4874acee-9c6e-4e47-99ad-e2ea1606961f`
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
                - password
                - h-captcha-response
              properties:
                email:
                  type: string
                password:
                  type: string
                h-captcha-response:
                  type: string
      responses:
        '200':
          description: 账号密码正确，设置 Cookies
          headers:
            Set-Cookie:
              description: 设置 cookies session
              schema:
                type: string
                example: sessionID=abcde12345; Path=/; HttpOnly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 请求错误或者验证码错误
          content:
            application/json:
              example:
                title: Bad Request
                details:
                  - Email为必填字段
                  - Password为必填字段
                  - HCaptchaResponse为必填字段
                description: can't validate request body
              schema:
                title: ErrorDetail
                required:
                  - title
                  - description
                  - detail
                type: object
                properties:
                  title:
                    title: Title
                    type: string
                  description:
                    title: Description
                    type: string
                  detail:
                    title: Detail
                    type: array
                    items:
                      type: string
        '401':
          description: 账号或密码错误
          content:
            application/json:
              schema:
                title: ErrorDetail
                required:
                  - title
                  - description
                  - detail
                type: object
                properties:
                  title:
                    title: Title
                    type: string
                  description:
                    title: Description
                    type: string
                  detail:
                    title: Detail
                    type: object
                    properties:
                      remain:
                        type: integer
                        description: 剩余可用登录次数。
        '422':
          description: 无法以 JSON 格式解析请求
        '502':
          description: hCaptcha HTTP 请求失败
  /p/logout:
    post:
      tags:
        - Auth
      summary: 登出
      operationId: logout
      security:
        - CookiesSession: []
      responses:
        '204':
          description: 正常登出
        '401':
          description: 用户未登录或者 session 已失效
components:
  schemas:
    User:
      example:
        avatar:
          large: https://lain.bgm.tv/pic/user/l/000/00/00/1.jpg?r=1391790456
          medium: https://lain.bgm.tv/pic/user/m/000/00/00/1.jpg?r=1391790456
          small: https://lain.bgm.tv/pic/user/s/000/00/00/1.jpg?r=1391790456
        sign: Awesome!
        url: https://bgm.tv/user/sai
        username: sai
        nickname: Sai🖖
        id: 1
        user_group: 1
      title: User
      required:
        - id
        - url
        - username
        - nickname
        - user_group
        - avatar
        - sign
      type: object
      properties:
        id:
          title: ID
          type: integer
        url:
          title: URL
          type: string
        username:
          title: Username
          type: string
          description: 唯一用户名，初始与 UID 相同，可修改一次
        nickname:
          title: Nickname
          type: string
        user_group:
          title: UserGroup
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 8
            - 9
            - 10
            - 11
          type: integer
          description: >-
            用户组 - 1 = 管理员 - 2 = Bangumi 管理猿 - 3 = 天窗管理猿 - 4 = 禁言用户 - 5 = 禁止访问用户
            - 8 = 人物管理猿 - 9 = 维基条目管理猿 - 10 = 用户 - 11 = 维基人
          x-ms-enum:
            name: UserGroup
            modelAsString: false
            values:
              - Admin
              - BangumiAdmin
              - DoujinAdmin
              - MutedUser
              - BlockedUser
              - PersonAdmin
              - WikiAdmin
              - User
              - WikiUser
          x-enum-varnames:
            - Admin
            - BangumiAdmin
            - DoujinAdmin
            - MutedUser
            - BlockedUser
            - PersonAdmin
            - WikiAdmin
            - User
            - WikiUser
        avatar:
          $ref: '#/components/schemas/Avatar'
        sign:
          title: Sign
          description: 个人签名
          type: string
    Avatar:
      title: Avatar
      required:
        - large
        - medium
        - small
      type: object
      properties:
        large:
          title: Large
          type: string
          format: url
        medium:
          title: Medium
          type: string
          format: url
        small:
          title: Small
          type: string
          format: url
    ErrorDetail:
      title: ErrorDetail
      required:
        - title
        - description
      type: object
      properties:
        title:
          title: Title
          type: string
        description:
          title: Description
          type: string
        detail:
          title: Detail
          oneOf:
            - type: string
            - type: object
              properties:
                error:
                  type: string
                  description: error message
                path:
                  type: string
                  description: request path
  securitySchemes:
    CookiesSession:
      name: sessionID
      type: apiKey
      in: cookie
