name: Fronend Dispatch
on:
  push:
    paths: [ 'api.yaml' ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: bangumi/frontend
          event-type: update-types
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
